
##############################################################
# Terminal Tools Configuration for "blocks-demo"
# Add environments under "Environments"
# Adjust the menu under "Menu" to your needs
##############################################################
Projectname: "blocks-demo"
Environments:
  Live:
    #required
    Host: ""
    Sshuser: "SSHUSER"
    Repodir: "REPODIR"
    #additional settings
    Domain: ""
    Sshport: ""
    Composerpath: ""
    PhpPath: ""
  Dev:
    #add dev site info here
Menu:
  Heading1:
    Title: Local
    Item1:
      Title: Pull code changes
      Command: "ttools/silverstripe/local/deploy.sh"
    Item2:
      Title: Back up content
      Command: "ttools/sitesync-core/local/backup.sh"
    Item3:
      Title: Update content from Dev Site
      Command: "ttools/sitesync-core/local/sync-environments.sh Dev Local"
    Item4:
      Title: Update content from Live Site
      Command: "ttools/sitesync-core/local/sync-environments.sh Live Local"
    Item5:
      Title: Revert content from backup
      Command: "ttools/sitesync-core/local/revert-from-backup.sh"
  Heading2:
    Title: Dev Site
    Item1:
      Title: SSH
      Command: "ttools/core/local/ssh.sh Dev"
    Item2:
      Title: Deploy
      Command: "ttools/silverstripe/local/deploy.sh Dev"
    Item3:
      Title: Push Local content
      Command: "ttools/sitesync-core/local/sync-environments.sh Local Dev"
    Item4:
      Title: Push Live content
      Command: "ttools/sitesync-core/local/sync-environments.sh Live Dev"      
  Heading3:
    Title: Live Site
    Item1:
      Title: SSH
      Command: "ttools/core/local/ssh.sh Live"
    Item2:
      Title: Deploy
      Command: "ttools/silverstripe/local/deploy.sh Live"
Sitesync:
  FrameworkModule: 'ttools/sitesync-silverstripe'


